/**
 * Orders Service
 * Handles all order creation operations (CAC payments and COD)
 * Separated from cacBankService since COD doesn't involve CAC Bank
 */

import { supabase } from '../lib/supabase';
import toast from 'react-hot-toast';

/**
 * Create order in Supabase (for CAC Bank payments)
 * @param {Object} orderData - Order details
 * @returns {Promise<Object>} Created order
 */
export const createOrder = async (orderData) => {
  try {
    const {
      userId,
      items,
      totalAmount,
      shippingAddress,
      phoneNumber,
      customerEmail,
      customerName
    } = orderData;

    // Use unified orders table with store_name
    const { data, error } = await supabase
      .from('orders')
      .insert([
        {
          customer_id: userId || null,
          user_id: userId || null,
          items: items,
          total_amount: totalAmount,
          currency: 'DJF',
          shipping_address: shippingAddress,
          customer_email: customerEmail,
          customer_name: customerName,
          customer_phone: phoneNumber || shippingAddress?.phone || shippingAddress?.phoneNumber,
          status: 'pending',
          payment_status: 'pending',
          payment_method: 'CAC Bank Mobile Money',
          delivery_status: 'pending',
          synced_to_erp: false,
          store_name: 'Urban Jungle' // Store identifier
          // created_at is auto-generated by database default
        }
      ])
      .select()
      .single();

    if (error) {
      console.error('❌ Supabase Insert Error:', error);
      throw error;
    }

    console.log('✅ Order created successfully:', data);

    return {
      success: true,
      order: data
    };
  } catch (error) {
    console.error('❌ Create Order Error:', error);
    console.error('Error details:', {
      message: error.message,
      details: error.details,
      hint: error.hint,
      code: error.code
    });
    toast.error('Failed to create order: ' + (error.message || 'Unknown error'));
    return {
      success: false,
      error: error.message
    };
  }
};

/**
 * Create Cash on Delivery (COD) order in Supabase
 * @param {Object} orderData - Order details
 * @returns {Promise<Object>} Created order
 */
export const createCODOrder = async (orderData) => {
  try {
    const {
      userId,
      items,
      totalAmount,
      shippingAddress,
      customerEmail,
      customerName
    } = orderData;

    console.log('💵 Creating COD order in orders table for Urban Jungle');

    // Extract phone from shippingAddress
    const customerPhone = shippingAddress?.phone || shippingAddress?.phoneNumber;

    // Use unified orders table with store_name
    const { data, error } = await supabase
      .from('orders')
      .insert([
        {
          customer_id: userId || null,
          user_id: userId || null,
          items: items,
          total_amount: totalAmount,
          currency: 'DJF',
          shipping_address: shippingAddress,
          customer_email: customerEmail,
          customer_name: customerName,
          customer_phone: customerPhone,
          status: 'pending', // Start as pending (matches constraint)
          payment_status: 'pending', // Will be paid on delivery
          payment_method: 'Cash on Delivery',
          delivery_status: 'pending',
          synced_to_erp: false,
          store_name: 'Urban Jungle' // Store identifier
        }
      ])
      .select()
      .single();

    if (error) {
      console.error('❌ Supabase COD Insert Error:', error);
      throw error;
    }

    console.log('✅ COD order created successfully:', data);

    // Auto-save address if user is logged in
    if (userId && shippingAddress) {
      try {
        const { autoSaveAddressAfterCheckout } = await import('./addressService');
        autoSaveAddressAfterCheckout(userId, data);
      } catch (addrError) {
        console.warn('⚠️ Address save failed (non-critical):', addrError);
      }
    }

    return {
      success: true,
      order: data
    };
  } catch (error) {
    console.error('❌ Create COD Order Error:', error);
    console.error('Error details:', {
      message: error.message,
      details: error.details,
      hint: error.hint,
      code: error.code
    });
    return {
      success: false,
      error: error.message
    };
  }
};

// Named export for backend.js compatibility
export const ordersService = {
  createOrder,
  createCODOrder
};
