// List of countries/nationalities for dropdown
export const countries = [
  { code: 'AF', name: 'Afghan' },
  { code: 'AL', name: 'Albanian' },
  { code: 'DZ', name: 'Algerian' },
  { code: 'AD', name: 'Andorran' },
  { code: 'AO', name: 'Angolan' },
  { code: 'AR', name: 'Argentine' },
  { code: 'AM', name: 'Armenian' },
  { code: 'AU', name: 'Australian' },
  { code: 'AT', name: 'Austrian' },
  { code: 'AZ', name: 'Azerbaijani' },
  { code: 'BS', name: 'Bahamian' },
  { code: 'BH', name: 'Bahraini' },
  { code: 'BD', name: 'Bangladeshi' },
  { code: 'BB', name: 'Barbadian' },
  { code: 'BY', name: 'Belarusian' },
  { code: 'BE', name: 'Belgian' },
  { code: 'BZ', name: 'Belizean' },
  { code: 'BJ', name: 'Beninese' },
  { code: 'BT', name: 'Bhutanese' },
  { code: 'BO', name: 'Bolivian' },
  { code: 'BA', name: 'Bosnian' },
  { code: 'BW', name: 'Botswanan' },
  { code: 'BR', name: 'Brazilian' },
  { code: 'BN', name: 'Bruneian' },
  { code: 'BG', name: 'Bulgarian' },
  { code: 'BF', name: 'Burkinabe' },
  { code: 'BI', name: 'Burundian' },
  { code: 'CV', name: 'Cape Verdean' },
  { code: 'KH', name: 'Cambodian' },
  { code: 'CM', name: 'Cameroonian' },
  { code: 'CA', name: 'Canadian' },
  { code: 'CF', name: 'Central African' },
  { code: 'TD', name: 'Chadian' },
  { code: 'CL', name: 'Chilean' },
  { code: 'CN', name: 'Chinese' },
  { code: 'CO', name: 'Colombian' },
  { code: 'KM', name: 'Comoran' },
  { code: 'CG', name: 'Congolese' },
  { code: 'CD', name: 'Congolese (DRC)' },
  { code: 'CR', name: 'Costa Rican' },
  { code: 'CI', name: 'Ivorian' },
  { code: 'HR', name: 'Croatian' },
  { code: 'CU', name: 'Cuban' },
  { code: 'CY', name: 'Cypriot' },
  { code: 'CZ', name: 'Czech' },
  { code: 'DK', name: 'Danish' },
  { code: 'DJ', name: 'Djiboutian' },
  { code: 'DM', name: 'Dominican' },
  { code: 'DO', name: 'Dominican (Republic)' },
  { code: 'EC', name: 'Ecuadorian' },
  { code: 'EG', name: 'Egyptian' },
  { code: 'SV', name: 'Salvadoran' },
  { code: 'GQ', name: 'Equatorial Guinean' },
  { code: 'ER', name: 'Eritrean' },
  { code: 'EE', name: 'Estonian' },
  { code: 'SZ', name: 'Swazi' },
  { code: 'ET', name: 'Ethiopian' },
  { code: 'FJ', name: 'Fijian' },
  { code: 'FI', name: 'Finnish' },
  { code: 'FR', name: 'French' },
  { code: 'GA', name: 'Gabonese' },
  { code: 'GM', name: 'Gambian' },
  { code: 'GE', name: 'Georgian' },
  { code: 'DE', name: 'German' },
  { code: 'GH', name: 'Ghanaian' },
  { code: 'GR', name: 'Greek' },
  { code: 'GD', name: 'Grenadian' },
  { code: 'GT', name: 'Guatemalan' },
  { code: 'GN', name: 'Guinean' },
  { code: 'GW', name: 'Guinea-Bissauan' },
  { code: 'GY', name: 'Guyanese' },
  { code: 'HT', name: 'Haitian' },
  { code: 'HN', name: 'Honduran' },
  { code: 'HU', name: 'Hungarian' },
  { code: 'IS', name: 'Icelandic' },
  { code: 'IN', name: 'Indian' },
  { code: 'ID', name: 'Indonesian' },
  { code: 'IR', name: 'Iranian' },
  { code: 'IQ', name: 'Iraqi' },
  { code: 'IE', name: 'Irish' },
  { code: 'IL', name: 'Israeli' },
  { code: 'IT', name: 'Italian' },
  { code: 'JM', name: 'Jamaican' },
  { code: 'JP', name: 'Japanese' },
  { code: 'JO', name: 'Jordanian' },
  { code: 'KZ', name: 'Kazakhstani' },
  { code: 'KE', name: 'Kenyan' },
  { code: 'KI', name: 'I-Kiribati' },
  { code: 'KP', name: 'North Korean' },
  { code: 'KR', name: 'South Korean' },
  { code: 'KW', name: 'Kuwaiti' },
  { code: 'KG', name: 'Kyrgyzstani' },
  { code: 'LA', name: 'Laotian' },
  { code: 'LV', name: 'Latvian' },
  { code: 'LB', name: 'Lebanese' },
  { code: 'LS', name: 'Basotho' },
  { code: 'LR', name: 'Liberian' },
  { code: 'LY', name: 'Libyan' },
  { code: 'LI', name: 'Liechtensteiner' },
  { code: 'LT', name: 'Lithuanian' },
  { code: 'LU', name: 'Luxembourgish' },
  { code: 'MG', name: 'Malagasy' },
  { code: 'MW', name: 'Malawian' },
  { code: 'MY', name: 'Malaysian' },
  { code: 'MV', name: 'Maldivian' },
  { code: 'ML', name: 'Malian' },
  { code: 'MT', name: 'Maltese' },
  { code: 'MH', name: 'Marshallese' },
  { code: 'MR', name: 'Mauritanian' },
  { code: 'MU', name: 'Mauritian' },
  { code: 'MX', name: 'Mexican' },
  { code: 'FM', name: 'Micronesian' },
  { code: 'MD', name: 'Moldovan' },
  { code: 'MC', name: 'Monégasque' },
  { code: 'MN', name: 'Mongolian' },
  { code: 'ME', name: 'Montenegrin' },
  { code: 'MA', name: 'Moroccan' },
  { code: 'MZ', name: 'Mozambican' },
  { code: 'MM', name: 'Burmese' },
  { code: 'NA', name: 'Namibian' },
  { code: 'NR', name: 'Nauruan' },
  { code: 'NP', name: 'Nepalese' },
  { code: 'NL', name: 'Dutch' },
  { code: 'NZ', name: 'New Zealander' },
  { code: 'NI', name: 'Nicaraguan' },
  { code: 'NE', name: 'Nigerien' },
  { code: 'NG', name: 'Nigerian' },
  { code: 'MK', name: 'North Macedonian' },
  { code: 'NO', name: 'Norwegian' },
  { code: 'OM', name: 'Omani' },
  { code: 'PK', name: 'Pakistani' },
  { code: 'PW', name: 'Palauan' },
  { code: 'PA', name: 'Panamanian' },
  { code: 'PG', name: 'Papua New Guinean' },
  { code: 'PY', name: 'Paraguayan' },
  { code: 'PE', name: 'Peruvian' },
  { code: 'PH', name: 'Filipino' },
  { code: 'PL', name: 'Polish' },
  { code: 'PT', name: 'Portuguese' },
  { code: 'QA', name: 'Qatari' },
  { code: 'RO', name: 'Romanian' },
  { code: 'RU', name: 'Russian' },
  { code: 'RW', name: 'Rwandan' },
  { code: 'KN', name: 'Kittitian/Nevisian' },
  { code: 'LC', name: 'Saint Lucian' },
  { code: 'VC', name: 'Vincentian' },
  { code: 'WS', name: 'Samoan' },
  { code: 'SM', name: 'Sammarinese' },
  { code: 'ST', name: 'São Toméan' },
  { code: 'SA', name: 'Saudi Arabian' },
  { code: 'SN', name: 'Senegalese' },
  { code: 'RS', name: 'Serbian' },
  { code: 'SC', name: 'Seychellois' },
  { code: 'SL', name: 'Sierra Leonean' },
  { code: 'SG', name: 'Singaporean' },
  { code: 'SK', name: 'Slovak' },
  { code: 'SI', name: 'Slovenian' },
  { code: 'SB', name: 'Solomon Islander' },
  { code: 'SO', name: 'Somali' },
  { code: 'ZA', name: 'South African' },
  { code: 'SS', name: 'South Sudanese' },
  { code: 'ES', name: 'Spanish' },
  { code: 'LK', name: 'Sri Lankan' },
  { code: 'SD', name: 'Sudanese' },
  { code: 'SR', name: 'Surinamese' },
  { code: 'SE', name: 'Swedish' },
  { code: 'CH', name: 'Swiss' },
  { code: 'SY', name: 'Syrian' },
  { code: 'TW', name: 'Taiwanese' },
  { code: 'TJ', name: 'Tajikistani' },
  { code: 'TZ', name: 'Tanzanian' },
  { code: 'TH', name: 'Thai' },
  { code: 'TL', name: 'Timorese' },
  { code: 'TG', name: 'Togolese' },
  { code: 'TO', name: 'Tongan' },
  { code: 'TT', name: 'Trinidadian/Tobagonian' },
  { code: 'TN', name: 'Tunisian' },
  { code: 'TR', name: 'Turkish' },
  { code: 'TM', name: 'Turkmen' },
  { code: 'TV', name: 'Tuvaluan' },
  { code: 'UG', name: 'Ugandan' },
  { code: 'UA', name: 'Ukrainian' },
  { code: 'AE', name: 'Emirati' },
  { code: 'GB', name: 'British' },
  { code: 'US', name: 'American' },
  { code: 'UY', name: 'Uruguayan' },
  { code: 'UZ', name: 'Uzbekistani' },
  { code: 'VU', name: 'Ni-Vanuatu' },
  { code: 'VA', name: 'Vatican' },
  { code: 'VE', name: 'Venezuelan' },
  { code: 'VN', name: 'Vietnamese' },
  { code: 'YE', name: 'Yemeni' },
  { code: 'ZM', name: 'Zambian' },
  { code: 'ZW', name: 'Zimbabwean' }
];

// Common nationalities in Djibouti (for prioritizing in dropdown)
export const commonNationalities = [
  'Djiboutian',
  'French', 
  'Ethiopian',
  'Somali',
  'Yemeni',
  'Eritrean'
];
